-- ============================================================
-- AUDIT FIXES — generated by automated audit 2026-05-04
-- Apply via Supabase SQL Editor: https://supabase.com/dashboard/project/ltwyduffgrbenghdzbji/sql/new
-- ============================================================

-- 1. Add missing columns to chat_messages
ALTER TABLE chat_messages
  ADD COLUMN IF NOT EXISTS updated_at    TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS upvotes_count INTEGER NOT NULL DEFAULT 0;

-- 2. Add missing columns to otp_codes
ALTER TABLE otp_codes
  ADD COLUMN IF NOT EXISTS attempts     INTEGER   NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_sent_at TIMESTAMPTZ;

-- Unique constraint on email for upsert (safe to re-add)
ALTER TABLE otp_codes
  DROP CONSTRAINT IF EXISTS otp_codes_email_key;
ALTER TABLE otp_codes
  ADD CONSTRAINT otp_codes_email_key UNIQUE (email);

-- 3. Add email_consent to chat_users (used in admin dashboard)
ALTER TABLE chat_users
  ADD COLUMN IF NOT EXISTS email_consent BOOLEAN NOT NULL DEFAULT false;

-- 4. Create bookmarked_messages table
CREATE TABLE IF NOT EXISTS bookmarked_messages (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES chat_users(id) ON DELETE CASCADE,
  message_id UUID        NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, message_id)
);
ALTER TABLE bookmarked_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bm: own" ON bookmarked_messages;
CREATE POLICY "bm: own" ON bookmarked_messages FOR ALL USING (true) WITH CHECK (true);

-- 5. Create pinned_messages table
CREATE TABLE IF NOT EXISTS pinned_messages (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id UUID        NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
  pinned_by  UUID        REFERENCES chat_users(id) ON DELETE SET NULL,
  pinned_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE pinned_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pm: all" ON pinned_messages;
CREATE POLICY "pm: all" ON pinned_messages FOR ALL USING (true) WITH CHECK (true);

-- 6. Create scheduled_messages table
CREATE TABLE IF NOT EXISTS scheduled_messages (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES chat_users(id) ON DELETE CASCADE,
  content      TEXT        NOT NULL,
  scheduled_at TIMESTAMPTZ NOT NULL,
  sent         BOOLEAN     NOT NULL DEFAULT false,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE scheduled_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "sm: own" ON scheduled_messages;
CREATE POLICY "sm: own" ON scheduled_messages FOR ALL USING (true) WITH CHECK (true);

-- 7. Create points_transactions table
CREATE TABLE IF NOT EXISTS points_transactions (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID        NOT NULL REFERENCES chat_users(id) ON DELETE CASCADE,
  amount     INTEGER     NOT NULL,
  reason     TEXT        NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE points_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "pt: own" ON points_transactions;
CREATE POLICY "pt: own" ON points_transactions FOR ALL USING (true) WITH CHECK (true);

-- ============================================================
-- Done. Safe to run multiple times (IF NOT EXISTS / IF EXISTS)
-- ============================================================
